feat(verify server): add verify server
Statsify/statsify pull request #152
Opened 2022-04-26 01:05 UTC by jacobk999

Makes progress on #136 

### TODO:
- [x] Make the server do something
- [x] Add server icon 
- [x] better messages

2022-04-26 02:02 UTC, eatmyvenom requested changes

2022-04-26 02:04 UTC, eatmyvenom reviewed
Can u add a vscode debug script for this too? I will look into if u need to specify a port to forward for devcontainer.

2022-04-27 00:43 UTC, jacobk999 commented
> Can u add a vscode debug script for this too? I will look into if u need to specify a port to forward for devcontainer.
Any update on this?

2022-04-27 00:46 UTC, ugcodrr approved these changes

2022-04-27 03:17 UTC, eatmyvenom commented
> Any update on this?

It appears to autodetect any ports and forward them automatically for you so you are good.

2022-04-27 17:17 UTC, eatmyvenom approved these changes

2022-04-27 20:54 UTC, merged