Feat/minecraft commands
Statsify/statsify pull request #212
Opened 2022-06-09 04:29 UTC by eatmyvenom

Description:
Related issues (if exists):

2022-06-09 14:29 UTC, jacobk999 requested changes

2022-06-09 14:29 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/colors.command.ts
> +        desc += `${modifiers.k} \`&k\` • ||${t('embeds.colors.description.obfuscated')}||\n`;
```suggestion
        desc += `${modifiers.k} \`&k\` • ${t('embeds.colors.description.obfuscated')}\n`;
```

2022-06-09 14:29 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/colors.command.ts
> +const colors: { [key: string]: string } = {
```suggestion
const colors: Record<string, string> = {
```

2022-06-09 14:29 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/colors.command.ts
> +const modifiers: { [key: string]: string } = {
```suggestion
const modifiers: Record<string, string> = {
```

2022-06-09 14:29 UTC, jacobk999 commented on apps/discord-bot/src/services/mojang-api.service.ts
> +  public async getName(uuid: string) {
```suggestion
  public async getPlayer(uuid: string) {
```

Make this return all the mojang player data, not just the name

2022-06-11 19:13 UTC, jacobk999 requested changes

2022-06-11 19:13 UTC, jacobk999 commented on apps/discord-bot/src/services/mojang-api.service.ts
> +    )}?size=160&default=MHF_Steve&overlay&id=c958a4c0ca23485299ffc2cab67aea3e`;
Make id a random uuid

2022-06-11 19:13 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/available.command.ts
> +          (t) => t('generic.available')
```suggestion
          (t) => t('available')
```

You don't actually have a generic field in the lang file

2022-06-11 19:13 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/available.command.ts
> +          (t) => t('generic.unavailable')
```suggestion
          (t) => t('unavailable')
```

Same thing as above

2022-06-11 19:13 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/available.command.ts
> +    const name = context.option<string>('player');
Add a check for if the name is actually a valid minecraft name. Currently we do something like `!name.match(/^\w+$/i) || name.length > 16`

2022-06-11 19:13 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/available.command.ts
> +export class AvailableCommand {
Use these colors:
Invalid - #b76ba3
Available - #00a28a
Unavailable - #f7c46c

2022-06-12 12:11 UTC, jacobk999 requested changes

2022-06-12 12:11 UTC, jacobk999 commented on apps/discord-bot/src/commands/minecraft/available.command.ts
> +export class AvailableCommand {
Can you add the information about the name's length on every embed. 

![Screenshot_20220612-080908_Discord.png](https://user-images.githubusercontent.com/42344274/173232430-a167b41b-2e0e-4ca9-aeba-9fe71a2deff3.png)

2022-06-13 23:33 UTC, jacobk999 approved these changes

2022-06-14 00:58 UTC, ugcodrr approved these changes

2022-06-14 01:40 UTC, ugcodrr approved these changes

2022-06-14 01:49 UTC, merged