feat(leaderboards): player leaderboards
Statsify/statsify pull request #27
Opened 2022-02-15 21:10 UTC by jacobk999

Closes #26 

### TODO:

- [ ] Ability to query different stats
- [ ] Ability to query relative to a player
- [ ] Pagination
- [ ] Input Validation
- [ ] Probably more

2022-02-24 03:23 UTC, eatmyvenom approved these changes

2022-02-24 03:23 UTC, ugcodrr approved these changes

2022-02-24 03:23 UTC, eatmyvenom approved these changes

2022-02-24 03:23 UTC, ugcodrr approved these changes

2022-02-25 00:45 UTC, ugcodrr approved these changes

2022-02-25 00:47 UTC, ugcodrr approved these changes

2022-02-25 00:48 UTC, eatmyvenom requested changes
Please document what the api properties are, for example "additionalFieldNames" is unclear as to its purpose.

2022-02-25 00:51 UTC, eatmyvenom approved these changes

2022-02-25 00:53 UTC, merged