feat(quests): add quest data, commands, and leaderboards
Statsify/statsify pull request #362
Opened 2022-08-08 04:19 UTC by eatmyvenom

## Todo
- [ ] Daily / Weekly design
- [ ] Ignore out of date players in daily / weekly leaderboards
- [ ] Add sidebar in historical?

2022-08-13 02:15 UTC, jacobk999 requested changes

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/arenabrawl.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Play Arena (Daily)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/arenabrawl.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Play Arena (Weekly)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/bedwars.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "One More Game!" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/bedwars.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Bed Removal Co." } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/bedwars.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Sleep Tight." } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/cops-and-crims.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Win a game! (Defusal)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/cops-and-crims.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Kill 15 players! (Defusal)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/cops-and-crims.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Get 300 points! (Deathmatch)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/cops-and-crims.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Win a game! (Deathmatch)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/cops-and-crims.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "100 kills and 1,500 points" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/quake.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Bazinga!" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/skywars.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Tokens!" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "TNT Run (Daily)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "PVP Run (Daily)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Bow Spleef (Daily)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "TNT Tag (Daily)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "TNT Wizards (Daily)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "TNT Run (Weekly)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "PVP Run (Weekly)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Bow Spleef (Weekly)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "TNT Tag (Weekly)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/tntgames.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "TNT Wizards (Weekly)" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/uhc.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Team UHC Champions" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/uhc.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Solo UHC Champions" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/uhc.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "UHC Deathmatch" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/uhc.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "UHC Champions" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/vampirez.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "VampireZ" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-13 02:15 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/general/quests/modes/warlords.ts
> +  @Field({ ...questFieldData, leaderboard: { name: "Carry, Secured!" } })
The leaderboard metadata won't get spread properly here because you overwrite the leaderboard field.

2022-08-21 21:19 UTC, jacobk999 requested changes

2022-08-21 21:19 UTC, jacobk999 commented on apps/discord-bot/src/commands/challenges/challenges.profile.tsx
> +  return <GameList entries={entries} gameIcons={gameIcons} rowSize={2} />;
```suggestion
  return <GameList entries={entries} gameIcons={gameIcons} />;
```

2022-08-21 21:19 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/index.ts
> +      name: "Total Quests Weekly",
```suggestion
      name: "Weekly Quests",
```

2022-08-21 21:19 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/index.ts
> +      name: "Total Quests Daily",
```suggestion
      name: "Daily Quests",
```

2022-08-21 21:19 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/cops-and-crims.ts
> +      propertyKey: "kill15Players",
Should this be 15 or 16?

2022-08-21 21:19 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/murdermystery.ts
> +    { field: "win", propertyKey: "daily_winner" },
I think `field` and `propertyKey` got flip flopped here. Something doesn't seem right.

2022-08-21 21:25 UTC, jacobk999 requested changes

2022-08-21 21:25 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/murdermystery.ts
> +    { field: "win", propertyKey: "daily_winner" },
I think `field` and `propertyKey` got flip flopped here. Something doesn't seem right.

2022-08-21 21:25 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/murdermystery.ts
> +    { field: "power_play", propertyKey: "daily_powerPlay" },
I think `field` and `propertyKey` got flip flopped here. Something doesn't seem right.

2022-08-21 21:25 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/murdermystery.ts
> +    { field: "target_kill", propertyKey: "daily_hitman" },
I think `field` and `propertyKey` got flip flopped here. Something doesn't seem right.

2022-08-21 21:25 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/murdermystery.ts
> +    { field: "infector", propertyKey: "daily_infector" },
I think `field` and `propertyKey` got flip flopped here. Something doesn't seem right.

2022-08-21 21:27 UTC, jacobk999 requested changes

2022-08-21 21:27 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/cops-and-crims.ts
> +      name: "Kill 16 Players! (Defusal)",
```suggestion
      name: "Kill 15 Players! (Defusal)",
```

2022-08-21 21:27 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/quests/modes/cops-and-crims.ts
> +      fieldName: "Kill 16 Players",
```suggestion
      fieldName: "Kill 15 Players",
```

2022-08-22 00:02 UTC, jacobk999 approved these changes

2022-08-22 00:13 UTC, ugcodrr approved these changes

2022-08-22 00:27 UTC, merged

2022-08-22 00:27 UTC, jacobk999 commented
🥳 🎉