feat(SpeedUHC): add speeduhc mastery leaderboards and stats
Statsify/statsify pull request #75
Opened 2022-03-05 04:51 UTC by eatmyvenom

2022-03-06 21:29 UTC, ugcodrr requested changes
Fix `fortune` mastery, right now it uses huntsman data.

    this.huntsman = new SpeedUHCMastery(data, 'huntsman');
    this.fortune = new SpeedUHCMastery(data, 'huntsman');

2022-03-06 23:41 UTC, jacobk999 requested changes

2022-03-06 23:41 UTC, jacobk999 commented on packages/schemas/src/player/gamemodes/speeduhc/mastery.ts
> +    mastery = mastery ? `_mastery_${mastery}` : mastery;
Is there a point to this line? When would you be inputting a blank mastery.

2022-03-08 04:17 UTC, ugcodrr approved these changes
W

2022-03-08 04:17 UTC, merged